export const SUBMISSION_FORM_FIELDS = {
  PRICE: 'price',
  CURRENCY: 'currency',
  DATE: 'date',
  WATER_UNIT: 'water_unit',
  PRICE_TYPE: 'price_type',
  USER_SECTOR: 'user_sector',
  INDIGENOUS_TERRITORY: 'indigenous_territory',
  COUNTRY: 'country',
  REGION: 'region',
  DATA_SOURCE: 'data_source',
  SOURCE_URL: 'source_url',
  SOURCE_TITLE: 'source_title',
  SOURCE_DATE: 'source_data',
  SOURCE_DESCRIPTION: 'source_description',
  SOURCE_AUTHORS: 'source_authors',
};

export const SUBMISSION_FORM_INITIAL_VALUES = {
  [SUBMISSION_FORM_FIELDS.PRICE]: null,
  [SUBMISSION_FORM_FIELDS.CURRENCY]: '',
  [SUBMISSION_FORM_FIELDS.DATE]: null,
  [SUBMISSION_FORM_FIELDS.WATER_UNIT]: '',
  [SUBMISSION_FORM_FIELDS.PRICE_TYPE]: '',
  [SUBMISSION_FORM_FIELDS.USER_SECTOR]: '',
  [SUBMISSION_FORM_FIELDS.INDIGENOUS_TERRITORY]: '',
  [SUBMISSION_FORM_FIELDS.COUNTRY]: '',
  [SUBMISSION_FORM_FIELDS.REGION]: '',
  [SUBMISSION_FORM_FIELDS.DATA_SOURCE]: '',
  [SUBMISSION_FORM_FIELDS.SOURCE_URL]: '',
  [SUBMISSION_FORM_FIELDS.SOURCE_TITLE]: '',
  [SUBMISSION_FORM_FIELDS.SOURCE_DESCRIPTION]: '',
  [SUBMISSION_FORM_FIELDS.SOURCE_DATE]: null,
  [SUBMISSION_FORM_FIELDS.SOURCE_AUTHORS]: '',
};

export const AUTHOR_ROLES = [
  {
    value: 'supplier',
    label: 'Supplier'
  },
  {
    value: 'user',
    label: 'User'
  },
  {
    value: 'regulator',
    label: 'Regulator'
  },
  {
    value: 'reporter',
    label: 'Reporter'
  }
]

export const PRICE_TYPES = [
  {
    value: 'statutory_price',
    label: 'Statutory price'
  },
  {
    value: 'transactional_price',
    label: 'Transactional price'
  },
  {
    value: 'environmental_value',
    label: 'Environmental value'
  },
  {
    value: 'derived_value',
    label: 'Derived value'
  },
];

export const WATER_UNITS = [
  {
    value: 'cubic_meter',
    label: 'Cubic meter'
  },
  {
    value: 'liter',
    label: 'Liter'
  },
  {
    value: 'acre_foot',
    label: 'Acre foot'
  },
  {
    value: 'gallon',
    label: 'Gallon'
  },
  {
    value: '1000_ccf',
    label: '1000 CCF'
  },
  {
    value: '100_cubic_meter',
    label: '100 cubic meter'
  },
  {
    value: 'ml',
    label: 'mL'
  },
  {
    value: 'kgal',
    label: 'kGal'
  },
];

export const USER_SECTORS = [
  {
    value: 'naics_11',
    code: 'NAICS 11',
    name: 'Agriculture, Forestry, Fishing and Hunting'
  },
  {
    value: 'naics_21',
    code: 'NAICS 21',
    name: 'Mining, Quarrying, and Oil and Gas Extraction'
  },
  {
    value: 'naics_22',
    code: 'NAICS 22',
    name: 'Utilies'
  },
  {
    value: 'naics_23',
    code: 'NAICS 23',
    name: 'Construction'
  },
  {
    value: 'naics_31-33',
    code: 'NAICS 31-33',
    name: 'Manufacturing'
  },
  {
    value: 'naics_42',
    code: 'NAICS 42',
    name: 'Wholesale Trade'
  },
  {
    value: 'naics_44-45',
    code: 'NAICS 44-45',
    name: 'Retail Trade'
  },
  {
    value: 'naics_48-49',
    code: 'NAICS 48-49',
    name: 'Transportation and Warehousing'
  },
  {
    value: 'naics_51',
    code: 'NAICS 51',
    name: 'Information'
  },
  {
    value: 'naics_52',
    code: 'NAICS 52',
    name: 'Finance and Insurance'
  },
  {
    value: 'naics_53',
    code: 'NAICS 53',
    name: 'Real Estate and Rental and Leasing'
  },
  {
    value: 'naics_54',
    code: 'NAICS 54',
    name: 'Professional, Scientific, and Technical Services'
  },
  {
    value: 'naics_55',
    code: 'NAICS 55',
    name: 'Management of Companies and Enterprises'
  },
  {
    value: 'naics_56',
    code: 'NAICS 56',
    name: 'Adminstrative and Support and Waste Management'
  },
  {
    value: 'naics_61',
    code: 'NAICS 61',
    name: 'Educational Services'
  },
  {
    value: 'naics_62',
    code: 'NAICS 62',
    name: 'Health Care and Social Assistance'
  },
  {
    value:'naics_71',
    code: 'NAICS 71',
    name: 'Arts, Entertainment, and Recreation'
  },
  {
    value: 'naics_72',
    code: 'NAICS 72',
    name: 'Accomodation and Food Services'
  },
  {
    value: 'naics_81',
    code: 'NAICS 81',
    name: 'Other Services (except Public Administration'
  },
  {
    value: 'naics_92',
    code: 'NAICS 92',
    name: 'Public Administration'
  },
];

export const CURRENCIES = [
  {"cc":"AED","symbol":"\u062f.\u0625;","name":"UAE dirham"},
  {"cc":"AFN","symbol":"Afs","name":"Afghan afghani"},
  {"cc":"ALL","symbol":"L","name":"Albanian lek"},
  {"cc":"AMD","symbol":"AMD","name":"Armenian dram"},
  {"cc":"ANG","symbol":"NA\u0192","name":"Netherlands Antillean gulden"},
  {"cc":"AOA","symbol":"Kz","name":"Angolan kwanza"},
  {"cc":"ARS","symbol":"$","name":"Argentine peso"},
  {"cc":"AUD","symbol":"$","name":"Australian dollar"},
  {"cc":"AWG","symbol":"\u0192","name":"Aruban florin"},
  {"cc":"AZN","symbol":"AZN","name":"Azerbaijani manat"},
  {"cc":"BAM","symbol":"KM","name":"Bosnia and Herzegovina konvertibilna marka"},
  {"cc":"BBD","symbol":"Bds$","name":"Barbadian dollar"},
  {"cc":"BDT","symbol":"\u09f3","name":"Bangladeshi taka"},
  {"cc":"BGN","symbol":"BGN","name":"Bulgarian lev"},
  {"cc":"BHD","symbol":".\u062f.\u0628","name":"Bahraini dinar"},
  {"cc":"BIF","symbol":"FBu","name":"Burundi franc"},
  {"cc":"BMD","symbol":"BD$","name":"Bermudian dollar"},
  {"cc":"BND","symbol":"B$","name":"Brunei dollar"},
  {"cc":"BOB","symbol":"Bs.","name":"Bolivian boliviano"},
  {"cc":"BRL","symbol":"R$","name":"Brazilian real"},
  {"cc":"BSD","symbol":"B$","name":"Bahamian dollar"},
  {"cc":"BTN","symbol":"Nu.","name":"Bhutanese ngultrum"},
  {"cc":"BWP","symbol":"P","name":"Botswana pula"},
  {"cc":"BYR","symbol":"Br","name":"Belarusian ruble"},
  {"cc":"BZD","symbol":"BZ$","name":"Belize dollar"},
  {"cc":"CAD","symbol":"$","name":"Canadian dollar"},
  {"cc":"CDF","symbol":"F","name":"Congolese franc"},
  {"cc":"CHF","symbol":"Fr.","name":"Swiss franc"},
  {"cc":"CLP","symbol":"$","name":"Chilean peso"},
  {"cc":"CNY","symbol":"\u00a5","name":"Chinese/Yuan renminbi"},
  {"cc":"COP","symbol":"Col$","name":"Colombian peso"},
  {"cc":"CRC","symbol":"\u20a1","name":"Costa Rican colon"},
  {"cc":"CUC","symbol":"$","name":"Cuban peso"},
  {"cc":"CVE","symbol":"Esc","name":"Cape Verdean escudo"},
  {"cc":"CZK","symbol":"K\u010d","name":"Czech koruna"},
  {"cc":"DJF","symbol":"Fdj","name":"Djiboutian franc"},
  {"cc":"DKK","symbol":"Kr","name":"Danish krone"},
  {"cc":"DOP","symbol":"RD$","name":"Dominican peso"},
  {"cc":"DZD","symbol":"\u062f.\u062c","name":"Algerian dinar"},
  {"cc":"EEK","symbol":"KR","name":"Estonian kroon"},
  {"cc":"EGP","symbol":"\u00a3","name":"Egyptian pound"},
  {"cc":"ERN","symbol":"Nfa","name":"Eritrean nakfa"},
  {"cc":"ETB","symbol":"Br","name":"Ethiopian birr"},
  {"cc":"EUR","symbol":"\u20ac","name":"European Euro"},
  {"cc":"FJD","symbol":"FJ$","name":"Fijian dollar"},
  {"cc":"FKP","symbol":"\u00a3","name":"Falkland Islands pound"},
  {"cc":"GBP","symbol":"\u00a3","name":"British pound"},
  {"cc":"GEL","symbol":"GEL","name":"Georgian lari"},
  {"cc":"GHS","symbol":"GH\u20b5","name":"Ghanaian cedi"},
  {"cc":"GIP","symbol":"\u00a3","name":"Gibraltar pound"},
  {"cc":"GMD","symbol":"D","name":"Gambian dalasi"},
  {"cc":"GNF","symbol":"FG","name":"Guinean franc"},
  {"cc":"GQE","symbol":"CFA","name":"Central African CFA franc"},
  {"cc":"GTQ","symbol":"Q","name":"Guatemalan quetzal"},
  {"cc":"GYD","symbol":"GY$","name":"Guyanese dollar"},
  {"cc":"HKD","symbol":"HK$","name":"Hong Kong dollar"},
  {"cc":"HNL","symbol":"L","name":"Honduran lempira"},
  {"cc":"HRK","symbol":"kn","name":"Croatian kuna"},
  {"cc":"HTG","symbol":"G","name":"Haitian gourde"},
  {"cc":"HUF","symbol":"Ft","name":"Hungarian forint"},
  {"cc":"IDR","symbol":"Rp","name":"Indonesian rupiah"},
  {"cc":"ILS","symbol":"\u20aa","name":"Israeli new sheqel"},
  {"cc":"INR","symbol":"\u20B9","name":"Indian rupee"},
  {"cc":"IQD","symbol":"\u062f.\u0639","name":"Iraqi dinar"},
  {"cc":"IRR","symbol":"IRR","name":"Iranian rial"},
  {"cc":"ISK","symbol":"kr","name":"Icelandic kr\u00f3na"},
  {"cc":"JMD","symbol":"J$","name":"Jamaican dollar"},
  {"cc":"JOD","symbol":"JOD","name":"Jordanian dinar"},
  {"cc":"JPY","symbol":"\u00a5","name":"Japanese yen"},
  {"cc":"KES","symbol":"KSh","name":"Kenyan shilling"},
  {"cc":"KGS","symbol":"\u0441\u043e\u043c","name":"Kyrgyzstani som"},
  {"cc":"KHR","symbol":"\u17db","name":"Cambodian riel"},
  {"cc":"KMF","symbol":"KMF","name":"Comorian franc"},
  {"cc":"KPW","symbol":"W","name":"North Korean won"},
  {"cc":"KRW","symbol":"W","name":"South Korean won"},
  {"cc":"KWD","symbol":"KWD","name":"Kuwaiti dinar"},
  {"cc":"KYD","symbol":"KY$","name":"Cayman Islands dollar"},
  {"cc":"KZT","symbol":"T","name":"Kazakhstani tenge"},
  {"cc":"LAK","symbol":"KN","name":"Lao kip"},
  {"cc":"LBP","symbol":"\u00a3","name":"Lebanese lira"},
  {"cc":"LKR","symbol":"Rs","name":"Sri Lankan rupee"},
  {"cc":"LRD","symbol":"L$","name":"Liberian dollar"},
  {"cc":"LSL","symbol":"M","name":"Lesotho loti"},
  {"cc":"LTL","symbol":"Lt","name":"Lithuanian litas"},
  {"cc":"LVL","symbol":"Ls","name":"Latvian lats"},
  {"cc":"LYD","symbol":"LD","name":"Libyan dinar"},
  {"cc":"MAD","symbol":"MAD","name":"Moroccan dirham"},
  {"cc":"MDL","symbol":"MDL","name":"Moldovan leu"},
  {"cc":"MGA","symbol":"FMG","name":"Malagasy ariary"},
  {"cc":"MKD","symbol":"MKD","name":"Macedonian denar"},
  {"cc":"MMK","symbol":"K","name":"Myanma kyat"},
  {"cc":"MNT","symbol":"\u20ae","name":"Mongolian tugrik"},
  {"cc":"MOP","symbol":"P","name":"Macanese pataca"},
  {"cc":"MRO","symbol":"UM","name":"Mauritanian ouguiya"},
  {"cc":"MUR","symbol":"Rs","name":"Mauritian rupee"},
  {"cc":"MVR","symbol":"Rf","name":"Maldivian rufiyaa"},
  {"cc":"MWK","symbol":"MK","name":"Malawian kwacha"},
  {"cc":"MXN","symbol":"$","name":"Mexican peso"},
  {"cc":"MYR","symbol":"RM","name":"Malaysian ringgit"},
  {"cc":"MZM","symbol":"MTn","name":"Mozambican metical"},
  {"cc":"NAD","symbol":"N$","name":"Namibian dollar"},
  {"cc":"NGN","symbol":"\u20a6","name":"Nigerian naira"},
  {"cc":"NIO","symbol":"C$","name":"Nicaraguan c\u00f3rdoba"},
  {"cc":"NOK","symbol":"kr","name":"Norwegian krone"},
  {"cc":"NPR","symbol":"NRs","name":"Nepalese rupee"},
  {"cc":"NZD","symbol":"NZ$","name":"New Zealand dollar"},
  {"cc":"OMR","symbol":"OMR","name":"Omani rial"},
  {"cc":"PAB","symbol":"B./","name":"Panamanian balboa"},
  {"cc":"PEN","symbol":"S/.","name":"Peruvian nuevo sol"},
  {"cc":"PGK","symbol":"K","name":"Papua New Guinean kina"},
  {"cc":"PHP","symbol":"\u20b1","name":"Philippine peso"},
  {"cc":"PKR","symbol":"Rs.","name":"Pakistani rupee"},
  {"cc":"PLN","symbol":"z\u0142","name":"Polish zloty"},
  {"cc":"PYG","symbol":"\u20b2","name":"Paraguayan guarani"},
  {"cc":"QAR","symbol":"QR","name":"Qatari riyal"},
  {"cc":"RON","symbol":"L","name":"Romanian leu"},
  {"cc":"RSD","symbol":"din.","name":"Serbian dinar"},
  {"cc":"RUB","symbol":"R","name":"Russian ruble"},
  {"cc":"SAR","symbol":"SR","name":"Saudi riyal"},
  {"cc":"SBD","symbol":"SI$","name":"Solomon Islands dollar"},
  {"cc":"SCR","symbol":"SR","name":"Seychellois rupee"},
  {"cc":"SDG","symbol":"SDG","name":"Sudanese pound"},
  {"cc":"SEK","symbol":"kr","name":"Swedish krona"},
  {"cc":"SGD","symbol":"S$","name":"Singapore dollar"},
  {"cc":"SHP","symbol":"\u00a3","name":"Saint Helena pound"},
  {"cc":"SLL","symbol":"Le","name":"Sierra Leonean leone"},
  {"cc":"SOS","symbol":"Sh.","name":"Somali shilling"},
  {"cc":"SRD","symbol":"$","name":"Surinamese dollar"},
  {"cc":"SYP","symbol":"LS","name":"Syrian pound"},
  {"cc":"SZL","symbol":"E","name":"Swazi lilangeni"},
  {"cc":"THB","symbol":"\u0e3f","name":"Thai baht"},
  {"cc":"TJS","symbol":"TJS","name":"Tajikistani somoni"},
  {"cc":"TMT","symbol":"m","name":"Turkmen manat"},
  {"cc":"TND","symbol":"DT","name":"Tunisian dinar"},
  {"cc":"TRY","symbol":"TRY","name":"Turkish new lira"},
  {"cc":"TTD","symbol":"TT$","name":"Trinidad and Tobago dollar"},
  {"cc":"TWD","symbol":"NT$","name":"New Taiwan dollar"},
  {"cc":"TZS","symbol":"TZS","name":"Tanzanian shilling"},
  {"cc":"UAH","symbol":"UAH","name":"Ukrainian hryvnia"},
  {"cc":"UGX","symbol":"USh","name":"Ugandan shilling"},
  {"cc":"USD","symbol":"US$","name":"United States dollar"},
  {"cc":"UYU","symbol":"$U","name":"Uruguayan peso"},
  {"cc":"UZS","symbol":"UZS","name":"Uzbekistani som"},
  {"cc":"VEB","symbol":"Bs","name":"Venezuelan bolivar"},
  {"cc":"VND","symbol":"\u20ab","name":"Vietnamese dong"},
  {"cc":"VUV","symbol":"VT","name":"Vanuatu vatu"},
  {"cc":"WST","symbol":"WS$","name":"Samoan tala"},
  {"cc":"XAF","symbol":"CFA","name":"Central African CFA franc"},
  {"cc":"XCD","symbol":"EC$","name":"East Caribbean dollar"},
  {"cc":"XDR","symbol":"SDR","name":"Special Drawing Rights"},
  {"cc":"XOF","symbol":"CFA","name":"West African CFA franc"},
  {"cc":"XPF","symbol":"F","name":"CFP franc"},
  {"cc":"YER","symbol":"YER","name":"Yemeni rial"},
  {"cc":"ZAR","symbol":"R","name":"South African rand"},
  {"cc":"ZMK","symbol":"ZK","name":"Zambian kwacha"},
  {"cc":"ZWR","symbol":"Z$","name":"Zimbabwean dollar"}
];

export const SEARCH_FORM_FIELDS = {
  COUNTRY: 'COUNTRY',
  REGION: 'REGION',
  EARLIEST_YEAR: 'EARLIEST_YEAR',
  LATEST_YEAR: 'LATEST_YEAR',
  USER_SECTOR: 'USER_SECTOR',
  WATER_TREATMENT: 'WATER_TREATMENT'
};

export const SEARCH_FORM_INITIAL_VALUES = {
  [SEARCH_FORM_FIELDS.COUNTRY]: '',
  [SEARCH_FORM_FIELDS.REGION]: '',
  [SEARCH_FORM_FIELDS.EARLIEST_YEAR]: 0,
  [SEARCH_FORM_FIELDS.LATEST_YEAR]: 0,
  [SEARCH_FORM_FIELDS.USER_SECTOR]: '',
  [SEARCH_FORM_FIELDS.WATER_TREATMENT]: ''
}

export const COUNTRY_CODES = [
    {"name":"Afghanistan","let2":" AF","let3":"AFG"},
    {"name":"Albania","let2":"AL","let3":"ALB"},
    {"name":"Algeria","let2":"DZ","let3":"DZA"},
    {"name":"American Samoa","let2":"AS","let3":"ASM"},
    {"name":"Andorra","let2":"AD","let3":"AND"},
    {"name":"Angola","let2":"AO","let3":"AGO"},
    {"name":"Anguilla","let2":"AI","let3":"AIA"},
    {"name":"Antigua and Barbuda","let2":"AG","let3":"ATG"},
    {"name":"Argentina","let2":"AR","let3":"ARG"},
    {"name":"Armenia","let2":"AM","let3":"ARM"},
    {"name":"Aruba","let2":"AW","let3":"ABW"},
    {"name":"Australia","let2":"AU","let3":"AUS"},
    {"name":"Austria","let2":"AT","let3":"AUT"},
    {"name":"Azerbaijan","let2":"AZ","let3":"AZE"},
    {"name":"Bahamas","let2":"BS","let3":"BHS"},
    {"name":"Bahrain","let2":"BH","let3":"BHR"},
    {"name":"Bangladesh","let2":"BD","let3":"BGD"},
    {"name":"Barbados","let2":"BB","let3":"BRB"},
    {"name":"Belarus","let2":"BY","let3":"BLR"},
    {"name":"Belgium","let2":"BE","let3":"BEL"},
    {"name":"Belize","let2":"BZ","let3":"BLZ"},
    {"name":"Benin","let2":"BJ","let3":"BEN"},
    {"name":"Bermuda","let2":"BM","let3":"BMU"},
    {"name":"Bhutan","let2":"BT","let3":"BTN"},
    {"name":"Bolivia","let2":"BO","let3":"BOL"},
    {"name":"Bosnia and Herzegovina","let2":"BA","let3":"BIH"},
    {"name":"Botswana","let2":"BW","let3":"BWA"},
    {"name":"Brazil","let2":"BR","let3":"BRA"},
    {"name":"British Virgin Islands","let2":"VG","let3":"VGB"},
    {"name":"Brunei Darussalam","let2":"BN","let3":"BRN"},
    {"name":"Bulgaria","let2":"BG","let3":"BGR"},
    {"name":"Burkina Faso","let2":"BF","let3":"BFA"},
    {"name":"Burundi","let2":"BI","let3":"BDI"},
    {"name":"Cambodia","let2":"KH","let3":"KHM"},
    {"name":"Cameroon","let2":"CM","let3":"CMR"},
    {"name":"Canada","let2":"CA","let3":"CAN"},
    {"name":"Cape Verde","let2":"CV","let3":"CPV"},
    {"name":"Central African Republic","let2":"CF","let3":"CAF"},
    {"name":"Chad","let2":"TD","let3":"TCD"},
    {"name":"Chile","let2":"CL","let3":"CHL"},
    {"name":"China","let2":"CN","let3":"CHN"},
    {"name":"Hong Kong","let2":"HK","let3":" \n         HKG"},
    {"name":"Macao","let2":"MO","let3":"MAC"},
    {"name":"Colombia","let2":"CO","let3":"COL"},
    {"name":"Comoros","let2":"KM","let3":"COM"},
    {"name":"Congo","let2":"CG","let3":"COG"},
    {"name":"Costa Rica","let2":"CR","let3":"CRI"},
    {"name":"Côte d'Ivoire","let2":"CI","let3":"CIV"},
    {"name":"Croatia","let2":"HR","let3":"HRV"},
    {"name":"Cuba","let2":"CU","let3":"CUB"},
    {"name":"Cyprus","let2":"CY","let3":"CYP"},
    {"name":"Czech Republic","let2":"CZ","let3":"CZE"},
    {"name":"Denmark","let2":"DK","let3":"DNK"},
    {"name":"Djibouti","let2":"DJ","let3":"DJI"},
    {"name":"Dominica","let2":"DM","let3":"DMA"},
    {"name":"Dominican Republic","let2":"DO","let3":"DOM"},
    {"name":"Ecuador","let2":"EC","let3":"ECU"},
    {"name":"Egypt","let2":"EG","let3":"EGY"},
    {"name":"El Salvador","let2":"SV","let3":"SLV"},
    {"name":"Equatorial Guinea","let2":"GQ","let3":"GNQ"},
    {"name":"Eritrea","let2":"ER","let3":"ERI"},
    {"name":"Estonia","let2":"EE","let3":"EST"},
    {"name":"Ethiopia","let2":"ET","let3":"ETH"},
    {"name":"Faroe Islands","let2":"FO","let3":" \n      FRO"},
    {"name":"Fiji","let2":"FJ","let3":"FJI"},
    {"name":"Finland","let2":"FI","let3":"FIN"},
    {"name":"France","let2":"FR","let3":"FRA"},
    {"name":"French Guiana","let2":"GF","let3":"GUF"},
    {"name":"French Polynesia","let2":"PF","let3":"PYF"},
    {"name":"Gabon","let2":"GA","let3":"GAB"},
    {"name":"Gambia","let2":"GM","let3":"GMB"},
    {"name":"Georgia","let2":"GE","let3":"GEO"},
    {"name":"Germany","let2":"DE","let3":"DEU"},
    {"name":"Ghana","let2":"GH","let3":"GHA"},
    {"name":"Greece","let2":"GR","let3":"GRC"},
    {"name":"Greenland","let2":"GL","let3":"GRL"},
    {"name":"Grenada","let2":"GD","let3":"GRD"},
    {"name":"Guadeloupe","let2":"GP","let3":"GLP"},
    {"name":"Guam","let2":"GU","let3":"GUM"},
    {"name":"Guatemala","let2":"GT","let3":"GTM"},
    {"name":"Guinea-Bissau","let2":"GW","let3":"GNB"},
    {"name":"Haiti","let2":"HT","let3":"HTI"},
    {"name":"Honduras","let2":"HN","let3":"HND"},
    {"name":"Iceland","let2":"IS","let3":"ISL"},
    {"name":"Indonesia","let2":"ID","let3":"IDN"},
    {"name":"Iraq","let2":"IQ","let3":"IRQ"},
    {"name":"Italy","let2":"IT","let3":"ITA"},
    {"name":"Japan","let2":"JP","let3":"JPN"},
    {"name":"Jordan","let2":"JO","let3":"JOR"},
    {"name":"Kazakhstan","let2":"KZ","let3":"KAZ"},
    {"name":"Kenya","let2":"KE","let3":"KEN"},
    {"name":"Kiribati","let2":"KI","let3":"KIR"},
    {"name":"Korea","let2":"KP","let3":"PRK"},
    {"name":"Korea","let2":"KR","let3":"KOR"},
    {"name":"Kuwait","let2":"KW","let3":"KWT"},
    {"name":"Kyrgyzstan","let2":"KG","let3":"KGZ"},
    {"name":"Lao PDR","let2":"LA","let3":"LAO"},
    {"name":"Latvia","let2":"LV","let3":"LVA"},
    {"name":"Lebanon","let2":"LB","let3":"LBN"},
    {"name":"Lesotho","let2":"LS","let3":"LSO"},
    {"name":"Liberia","let2":"LR","let3":"LBR"},
    {"name":"Libya","let2":"LY","let3":"LBY"},
    {"name":"Liechtenstein","let2":"LI","let3":"LIE"},
    {"name":"Lithuania","let2":"LT","let3":"LTU"},
    {"name":"Luxembourg","let2":"LU","let3":"LUX"},
    {"name":"Madagascar","let2":"MG","let3":"MDG"},
    {"name":"Malawi","let2":"MW","let3":"MWI"},
    {"name":"Malaysia","let2":"MY","let3":"MYS"},
    {"name":"Maldives","let2":"MV","let3":"MDV"},
    {"name":"Mali","let2":"ML","let3":"MLI"},
    {"name":"Malta","let2":"MT","let3":"MLT"},
    {"name":"Marshall Islands","let2":"MH","let3":"MHL"},
    {"name":"Martinique","let2":"MQ","let3":"MTQ"},
    {"name":"Mauritania","let2":"MR","let3":"MRT"},
    {"name":"Mauritius","let2":"MU","let3":"MUS"},
    {"name":"Mexico","let2":"MX","let3":"MEX"},
    {"name":"Micronesia, Federated States of","let2":"FM","let3":"FSM"},
    {"name":"Moldova","let2":"MD","let3":"MDA"},
    {"name":"Monaco","let2":"MC","let3":"MCO"},
    {"name":"Mongolia","let2":"MN","let3":"MNG"},
    {"name":"Montenegro","let2":"ME","let3":"MNE"},
    {"name":"Montserrat","let2":"MS","let3":"MSR"},
    {"name":"Morocco","let2":"MA","let3":"MAR"},
    {"name":"Mozambique","let2":"MZ","let3":"MOZ"},
    {"name":"Myanmar","let2":"MM","let3":"MMR"},
    {"name":"Namibia","let2":"NA","let3":"NAM"},
    {"name":"Nauru","let2":"NR","let3":"NRU"},
    {"name":"Nepal","let2":"NP","let3":"NPL"},
    {"name":"Netherlands","let2":"NL","let3":"NLD"},
    {"name":"Netherlands Antilles","let2":"AN","let3":"ANT"},
    {"name":"New Caledonia","let2":"NC","let3":"NCL"},
    {"name":"New Zealand","let2":"NZ","let3":"NZL"},
    {"name":"Nicaragua","let2":"NI","let3":"NIC"},
    {"name":"Niger","let2":"NE","let3":"NER"},
    {"name":"Nigeria","let2":"NG","let3":"NGA"},
    {"name":"Northern Mariana Islands","let2":"MP","let3":"MNP"},
    {"name":"Norway","let2":"NO","let3":"NOR"},
    {"name":"Oman","let2":"OM","let3":"OMN"},
    {"name":"Pakistan","let2":"PK","let3":"PAK"},
    {"name":"Palau","let2":"PW","let3":"PLW"},
    {"name":"Palestinian Territory","let2":"PS","let3":" \n      PSE"},
    {"name":"Panama","let2":"PA","let3":"PAN"},
    {"name":"Papua New Guinea","let2":"PG","let3":"PNG"},
    {"name":"Paraguay","let2":"PY","let3":"PRY"},
    {"name":"Peru","let2":"PE","let3":"PER"},
    {"name":"Philippines","let2":"PH","let3":"PHL"},
    {"name":"Pitcairn","let2":"PN","let3":"PCN"},
    {"name":"Poland","let2":"PL","let3":"POL"},
    {"name":"Portugal","let2":"PT","let3":"PRT"},
    {"name":"Puerto Rico","let2":"PR","let3":"PRI"},
    {"name":"Qatar","let2":"QA","let3":"QAT"},
    {"name":"Réunion","let2":"RE","let3":"REU"},
    {"name":"Romania","let2":"RO","let3":"ROU"},
    {"name":"Russian Federation","let2":"RU","let3":"RUS"},
    {"name":"Rwanda","let2":"RW","let3":"RWA"},
    {"name":"Saint Kitts and Nevis","let2":"KN","let3":"KNA"},
    {"name":"Saint Lucia","let2":"LC","let3":"LCA"},
    {"name":"Saint Vincent and Grenadines","let2":"VC","let3":"VCT"},
    {"name":"Samoa","let2":"WS","let3":"WSM"},
    {"name":"San Marino","let2":"SM","let3":"SMR"},
    {"name":"Sao Tome and Principe","let2":"ST","let3":"STP"},
    {"name":"Saudi Arabia","let2":"SA","let3":"SAU"},
    {"name":"Senegal","let2":"SN","let3":"SEN"},
    {"name":"Serbia","let2":"RS","let3":"SRB"},
    {"name":"Seychelles","let2":"SC","let3":"SYC"},
    {"name":"Sierra Leone","let2":"SL","let3":"SLE"},
    {"name":"Singapore","let2":"SG","let3":"SGP"},
    {"name":"Slovakia","let2":"SK","let3":"SVK"},
    {"name":"Slovenia","let2":"SI","let3":"SVN"},
    {"name":"Solomon Islands","let2":"SB","let3":"SLB"},
    {"name":"Somalia","let2":"SO","let3":"SOM"},
    {"name":"South Africa","let2":"ZA","let3":"ZAF"},
    {"name":"Spain","let2":"ES","let3":"ESP"},
    {"name":"Sri Lanka","let2":"LK","let3":"LKA"},
    {"name":"Sudan","let2":"SD","let3":"SDN"},
    {"name":"Suriname","let2":"SR","let3":"SUR"},
    {"name":"Swaziland","let2":"SZ","let3":"SWZ"},
    {"name":"Sweden","let2":"SE","let3":"SWE"},
    {"name":"Switzerland","let2":"CH","let3":"CHE"},
    {"name":"Syrian Arab Republic","let2":"SY","let3":"SYR"},
    {"name":"Tajikistan","let2":"TJ","let3":"TJK"},
    {"name":"Tanzania","let2":"TZ","let3":"TZA"},
    {"name":"Thailand","let2":"TH","let3":"THA"},
    {"name":"Timor-Leste","let2":"TL","let3":"TLS"},
    {"name":"Togo","let2":"TG","let3":"TGO"},
    {"name":"Tonga","let2":"TO","let3":"TON"},
    {"name":"Trinidad and Tobago","let2":"TT","let3":"TTO"},
    {"name":"Tunisia","let2":"TN","let3":"TUN"},
    {"name":"Turkey","let2":"TR","let3":"TUR"},
    {"name":"Turkmenistan","let2":"TM","let3":"TKM"},
    {"name":"Tuvalu","let2":"TV","let3":"TUV"},
    {"name":"Uganda","let2":"UG","let3":"UGA"},
    {"name":"Ukraine","let2":"UA","let3":"UKR"},
    {"name":"United Arab Emirates","let2":"AE","let3":"ARE"},
    {"name":"United Kingdom","let2":"GB","let3":"GBR"},
    {"name":"United States of America","let2":"US","let3":"USA"},
    {"name":"Uruguay","let2":"UY","let3":"URY"},
    {"name":"Uzbekistan","let2":"UZ","let3":"UZB"},
    {"name":"Vanuatu","let2":"VU","let3":"VUT"},
    {"name":"Venezuela","let2":"VE","let3":"VEN"},
    {"name":"Viet Nam","let2":"VN","let3":"VNM"},
    {"name":"Virgin Islands, US","let2":"VI","let3":"VIR"},
    {"name":"Yemen","let2":"YE","let3":"YEM"},
    {"name":"Zambia","let2":"ZM","let3":"ZMB"},
    {"name":"Zimbabwe","let2":"ZW","let3":"ZWE"}
];