export const FIELDS = {
  COUNTRY: 'COUNTRY',
  REGION: 'REGION',
  EARLIEST_YEAR: 'EARLIEST_YEAR',
  LATEST_YEAR: 'LATEST_YEAR',
  USER_SECTOR: 'USER_SECTOR',
  WATER_TREATMENT: 'WATER_TREATMENT'
};

export const INITIAL_VALUES = {
  [FIELDS.COUNTRY]: '',
  [FIELDS.REGION]: '',
  [FIELDS.EARLIEST_YEAR]: 0,
  [FIELDS.LATEST_YEAR]: 0,
  [FIELDS.USER_SECTOR]: '',
  [FIELDS.WATER_TREATMENT]: ''
}