export const data = [
    {
        'vp_num': 5,
        'vp_date':  2014,
        'vp_water_unit': 'Cubic Meter',
        'time': 'Annual',
        'type': 'Transactional price',
        'vp_water_treatment': 'Desalination',
        'regionSpecific': 'Chiapas',
        'indigenousTerritory': '',
        'src_title': 'TARIFAS VIGENTES PARA LECTURAS LEIDAS DESDE EL 31 de Julio 2018',
        'source_uri': 'https://www.nuevaatacama.cl/recursos-ata/Tarifas/Tarifa%20ACA%2031%20de%20Julio%202018.pdf',
        'currency_id': 'USD',
        'impactCode': '',
        'typeCode': '',
        'sourceCode': '',
        'regionName': 'Southern',
        'companyID': '',
        'communityID': '',
        'nhCode': '',
        'nation_id': 'MEX'
    },
    {
        'vp_num': 5,
        'vp_date':  2014,
        'vp_water_unit': 'Cubic Meter',
        'time': 'Annual',
        'type': 'Transactional price',
        'vp_water_treatment': 'Desalination',
        'regionSpecific': 'Chiapas',
        'indigenousTerritory': '',
        'src_title': 'TARIFAS VIGENTES PARA LECTURAS LEIDAS DESDE EL 31 de Julio 2018',
        'source_uri': 'https://www.nuevaatacama.cl/recursos-ata/Tarifas/Tarifa%20ACA%2031%20de%20Julio%202018.pdf',
        'currency_id': 'USD',
        'impactCode': '',
        'typeCode': '',
        'sourceCode': '',
        'regionName': 'Southern',
        'companyID': '',
        'communityID': '',
        'nhCode': '',
        'nation_id': 'MEX'
    },
    {
        'vp_num': 5,
        'vp_date':  2014,
        'vp_water_unit': 'Cubic Meter',
        'time': 'Annual',
        'type': 'Transactional price',
        'vp_water_treatment': 'Desalination',
        'regionSpecific': 'Chiapas',
        'indigenousTerritory': '',
        'src_title': 'TARIFAS VIGENTES PARA LECTURAS LEIDAS DESDE EL 31 de Julio 2018',
        'source_uri': 'https://www.nuevaatacama.cl/recursos-ata/Tarifas/Tarifa%20ACA%2031%20de%20Julio%202018.pdf',
        'currency_id': 'EUR',
        'impactCode': '',
        'typeCode': '',
        'sourceCode': '',
        'regionName': 'Southern',
        'companyID': '',
        'communityID': '',
        'nhCode': '',
        'nation_id': 'MEX'
    },
    {
        'vp_num': 1.2,
        'vp_date':  2011,
        'vp_water_unit': 'Cubic Meter',
        'time': 'Second',
        'type': 'Statutory price',
        'vp_water_treatment': 'Desalination',
        'regionSpecific': 'Chiapas',
        'indigenousTerritory': '',
        'src_title': 'TARIFAS VIGENTES PARA LECTURAS LEIDAS DESDE EL 31 de Julio 2018',
        'source_uri': 'https://www.nuevaatacama.cl/recursos-ata/Tarifas/Tarifa%20ACA%2031%20de%20Julio%202018.pdf',
        'currency_id': 'USD',
        'impactCode': '',
        'typeCode': '',
        'sourceCode': '',
        'regionName': 'Southern',
        'companyID': '',
        'communityID': '',
        'nhCode': '',
        'nation_id': 'MEX'
    },
    {
        'vp_num': 81,
        'vp_date':  2018,
        'vp_water_unit': 'Cubic Meter',
        'time': 'Annual',
        'type': 'Transactional price',
        'vp_water_treatment': 'Desalination',
        'regionSpecific': 'Chiapas',
        'indigenousTerritory': '',
        'src_title': 'TARIFAS VIGENTES PARA LECTURAS LEIDAS DESDE EL 31 de Julio 2018',
        'source_uri': 'https://www.nuevaatacama.cl/recursos-ata/Tarifas/Tarifa%20ACA%2031%20de%20Julio%202018.pdf',
        'currency_id': 'USD',
        'impactCode': '',
        'typeCode': '',
        'sourceCode': '',
        'regionName': 'Southern',
        'companyID': '',
        'communityID': '',
        'nhCode': '',
        'nation_id': 'MEX'
    }
    
]