export const data = [
  {
    'vp_num': 5,
    'vp_date':  2014,
    'vp_wtrunit': 'Cubic Meter',
    'type': 'Transactional price',
    'water_treatment': 'Desalination',
    'curr_code': 'USD',
    'nat_code': 'MEX',
    'source': {
      'source_uri': 'https://www.nuevaatacama.cl/recursos-ata/Tarifas/Tarifa%20ACA%2031%20de%20Julio%202018.pdf',
      'source_title': 'TARIFAS VIGENTES PARA LECTURAS LEIDAS DESDE EL 31 de Julio 2018',
      'source_date': 2014,
      'source_note': 'No notes',
      'source_belief': 'High',
      'source_creator': 'John Smith, Jane Doe',
    }
  },
  {
    'vp_num': 5,
    'vp_date':  2014,
    'vp_wtrunit': 'Cubic Meter',
    'type': 'Transactional price',
    'water_treatment': 'Desalination',
    'curr_code': 'USD',
    'nat_code': 'MEX',
    'source_uri': 'https://www.nuevaatacama.cl/recursos-ata/Tarifas/Tarifa%20ACA%2031%20de%20Julio%202018.pdf',
    'source_title': 'TARIFAS VIGENTES PARA LECTURAS LEIDAS DESDE EL 31 de Julio 2018',
    'source_date': 2014,
    'source_note': 'No notes',
    'source_belief': 'High',
    'source_creator': 'John Smith, Jane Doe',
  },
  {
    'vp_num': 5,
    'vp_date':  2014,
    'vp_wtrunit': 'Cubic Meter',
    'type': 'Transactional price',
    'water_treatment': 'Desalination',
    'curr_code': 'EUR',
    'nat_code': 'MEX',
    'source_uri': 'https://www.nuevaatacama.cl/recursos-ata/Tarifas/Tarifa%20ACA%2031%20de%20Julio%202018.pdf',
    'source_title': 'TARIFAS VIGENTES PARA LECTURAS LEIDAS DESDE EL 31 de Julio 2018',
    'source_date': 2014,
    'source_note': 'No notes',
    'source_belief': 'High',
    'source_creator': 'John Smith, Jane Doe',
  },
  {
    'vp_num': 1.2,
    'vp_date':  2011,
    'vp_wtrunit': 'Cubic Meter',
    'time': 'Second',
    'type': 'Statutory price',
    'water_treatment': 'Desalination',
    'curr_code': 'USD',
    'nat_code': 'MEX',
    'source_uri': 'https://www.nuevaatacama.cl/recursos-ata/Tarifas/Tarifa%20ACA%2031%20de%20Julio%202018.pdf',
    'source_title': 'TARIFAS VIGENTES PARA LECTURAS LEIDAS DESDE EL 31 de Julio 2018',
    'source_date': 2014,
    'source_note': 'No notes',
    'source_belief': 'High',
    'source_creator': 'John Smith, Jane Doe',
  },
  {
    'vp_num': 81,
    'vp_date':  2018,
    'vp_wtrunit': 'Cubic Meter',
    'type': 'Transactional price',
    'water_treatment': 'Desalination',
    'curr_code': 'USD',
    'nat_code': 'MEX',
    'source_uri': 'https://www.nuevaatacama.cl/recursos-ata/Tarifas/Tarifa%20ACA%2031%20de%20Julio%202018.pdf',
    'source_title': 'TARIFAS VIGENTES PARA LECTURAS LEIDAS DESDE EL 31 de Julio 2018',
    'source_date': 2014,
    'source_note': 'No notes',
    'source_belief': 'High',
    'source_creator': 'John Smith, Jane Doe',
  }
];