export const data = [
    {
        'price': 5,
        'date':  2014,
        'unit': 'Cubic Meter',
        'time': 'Annual',
        'type': 'Transactional price',
        'waterTreatment': 'Desalination',
        'regionSpecific': 'Chiapas',
        'indigenousTerritory': '',
        'sourceURI': 'https://www.nuevaatacama.cl/recursos-ata/Tarifas/Tarifa%20ACA%2031%20de%20Julio%202018.pdf',
        'currCode': 'LKR',
        'impactCode': '',
        'typeCode': '',
        'sourceCode': '',
        'regionName': 'Southern',
        'companyID': '',
        'communityID': '',
        'nhCode': '',
        'nationCode': 'MEX'
    },
    {
        'price': 5,
        'date':  2014,
        'unit': 'Cubic Meter',
        'time': 'Annual',
        'type': 'Transactional price',
        'waterTreatment': 'Desalination',
        'regionSpecific': 'Chiapas',
        'indigenousTerritory': '',
        'sourceURI': 'https://www.nuevaatacama.cl/recursos-ata/Tarifas/Tarifa%20ACA%2031%20de%20Julio%202018.pdf',
        'currCode': 'USD',
        'impactCode': '',
        'typeCode': '',
        'sourceCode': '',
        'regionName': 'Southern',
        'companyID': '',
        'communityID': '',
        'nhCode': '',
        'nationCode': 'LKA'
    },
    {
        'price': 5,
        'date':  2014,
        'unit': 'Cubic Meter',
        'time': 'Annual',
        'type': 'Transactional price',
        'waterTreatment': 'Desalination',
        'regionSpecific': 'Chiapas',
        'indigenousTerritory': '',
        'sourceURI': 'https://www.nuevaatacama.cl/recursos-ata/Tarifas/Tarifa%20ACA%2031%20de%20Julio%202018.pdf',
        'currCode': 'EUR',
        'impactCode': '',
        'typeCode': '',
        'sourceCode': '',
        'regionName': 'Southern',
        'companyID': '',
        'communityID': '',
        'nhCode': '',
        'nationCode': 'MEX'
    },
    {
        'price': 1.2,
        'date':  2011,
        'unit': 'Liter',
        'time': 'Second',
        'type': 'Statutory price',
        'waterTreatment': 'Desalination',
        'regionSpecific': 'Chiapas',
        'indigenousTerritory': '',
        'sourceURI': 'https://www.nuevaatacama.cl/recursos-ata/Tarifas/Tarifa%20ACA%2031%20de%20Julio%202018.pdf',
        'currCode': 'USD',
        'impactCode': '',
        'typeCode': '',
        'sourceCode': '',
        'regionName': 'Southern',
        'companyID': '',
        'communityID': '',
        'nhCode': '',
        'nationCode': 'MEX'
    },
    {
        'price': 81,
        'date':  2018,
        'unit': 'Cubic Meter',
        'time': 'Annual',
        'type': 'Transactional price',
        'waterTreatment': 'Desalination',
        'regionSpecific': 'Colombo',
        'indigenousTerritory': '',
        'sourceURI': 'https://www.nuevaatacama.cl/recursos-ata/Tarifas/Tarifa%20ACA%2031%20de%20Julio%202018.pdf',
        'currCode': 'USD',
        'impactCode': '',
        'typeCode': '',
        'sourceCode': '',
        'regionName': 'Southern',
        'companyID': '',
        'communityID': '',
        'nhCode': '',
        'nationCode': 'MEX'
    }
    
]